// <auto-generated />
using System;
using AtlantisSwim.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AtlantisSwim.DataAccess.Migrations
{
    [DbContext(typeof(DbSession))]
    [Migration("20260408023325_SeedMissingData")]
    partial class SeedMissingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AtlantisSwim.Domain.Entities.Course.CourseData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Enrolled")
                        .HasColumnType("integer");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 12,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A foundational course covering basic strokes and water safety.",
                            Enrolled = 0,
                            LevelId = 1,
                            Name = "Learn to Swim",
                            Price = 150.00m,
                            Schedule = "Mon, Wed 09:00",
                            UpdatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 10,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Focus on freestyle and breaststroke technique for intermediate swimmers.",
                            Enrolled = 0,
                            LevelId = 2,
                            Name = "Stroke Improvement",
                            Price = 200.00m,
                            Schedule = "Tue, Thu 18:00",
                            UpdatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 8,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-intensity training for competitive swimmers.",
                            Enrolled = 0,
                            LevelId = 3,
                            Name = "Competitive Training",
                            Price = 280.00m,
                            Schedule = "Mon, Wed, Fri 07:00",
                            UpdatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AtlantisSwim.Domain.Entities.Course.CourseImg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseDataId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseDataId");

                    b.ToTable("CourseImgs");
                });

            modelBuilder.Entity("AtlantisSwim.Domain.Entities.Course.CourseLevelData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CourseLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "For those with no prior swimming experience.",
                            Name = "Beginner"
                        },
                        new
                        {
                            Id = 2,
                            Description = "For swimmers comfortable in water.",
                            Name = "Intermediate"
                        },
                        new
                        {
                            Id = 3,
                            Description = "For experienced swimmers refining technique.",
                            Name = "Advanced"
                        });
                });

            modelBuilder.Entity("AtlantisSwim.Domain.Entities.Student.StudentData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("EnrolledOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("SwimmingLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2005, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maria.ionescu@email.com",
                            EnrolledOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Maria",
                            IsActive = true,
                            LastName = "Ionescu",
                            Phone = "0721000001",
                            SwimmingLevel = "Beginner"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2003, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "andrei.popescu@email.com",
                            EnrolledOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Andrei",
                            IsActive = true,
                            LastName = "Popescu",
                            Phone = "0721000002",
                            SwimmingLevel = "Intermediate"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2001, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "elena.constantin@email.com",
                            EnrolledOn = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Elena",
                            IsActive = true,
                            LastName = "Constantin",
                            Phone = "0721000003",
                            SwimmingLevel = "Advanced"
                        });
                });

            modelBuilder.Entity("AtlantisSwim.Domain.Entities.SwimmingService.SwimmingServiceData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("ServicePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SwimmingServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ServiceDescription = "One-on-one coaching sessions tailored to individual needs.",
                            ServiceName = "Private Lessons",
                            ServicePrice = 80.00m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ServiceDescription = "Small group lessons with up to 6 participants.",
                            ServiceName = "Group Classes",
                            ServicePrice = 40.00m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ServiceDescription = "Dedicated lane access for personal training sessions.",
                            ServiceName = "Pool Lane Rental",
                            ServicePrice = 25.00m
                        });
                });

            modelBuilder.Entity("AtlantisSwim.Domain.Entities.User.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@atlantisswim.ro",
                            FirstName = "Admin",
                            LastName = "Atlantis",
                            Password = "Admin@1234",
                            Phone = "0700000001",
                            RegisteredOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = 30,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "coach@atlantisswim.ro",
                            FirstName = "Ioan",
                            LastName = "Marinescu",
                            Password = "Coach@1234",
                            Phone = "0700000002",
                            RegisteredOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = 20,
                            UserName = "coach.ioan"
                        });
                });

            modelBuilder.Entity("AtlantisSwim.Domain.Entities.Course.CourseData", b =>
                {
                    b.HasOne("AtlantisSwim.Domain.Entities.Course.CourseLevelData", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("AtlantisSwim.Domain.Entities.Course.CourseImg", b =>
                {
                    b.HasOne("AtlantisSwim.Domain.Entities.Course.CourseData", null)
                        .WithMany("Imgs")
                        .HasForeignKey("CourseDataId");
                });

            modelBuilder.Entity("AtlantisSwim.Domain.Entities.Course.CourseData", b =>
                {
                    b.Navigation("Imgs");
                });
#pragma warning restore 612, 618
        }
    }
}
