// <auto-generated />
using System;
using AtlantisSwim.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AtlantisSwim.DataAccess.Migrations
{
    [DbContext(typeof(DbSession))]
    partial class DbSessionModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AtlantisSwim.Domain.Entities.Course.CourseData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Enrolled")
                        .HasColumnType("integer");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 12,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A foundational course covering basic strokes and water safety.",
                            Enrolled = 0,
                            LevelId = 1,
                            Name = "Learn to Swim",
                            Price = 150.00m,
                            Schedule = "Mon, Wed 09:00",
                            UpdatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 10,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Focus on freestyle and breaststroke technique for intermediate swimmers.",
                            Enrolled = 0,
                            LevelId = 2,
                            Name = "Stroke Improvement",
                            Price = 200.00m,
                            Schedule = "Tue, Thu 18:00",
                            UpdatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 8,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-intensity training for competitive swimmers.",
                            Enrolled = 0,
                            LevelId = 3,
                            Name = "Competitive Training",
                            Price = 280.00m,
                            Schedule = "Mon, Wed, Fri 07:00",
                            UpdatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 10,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Learn the basics of floating and kicking.",
                            Enrolled = 8,
                            LevelId = 1,
                            Name = "Beginner Swim - Kids",
                            Price = 250.00m,
                            Schedule = "Mon, Wed 16:00",
                            UpdatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 15,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Refine your technique for competition.",
                            Enrolled = 12,
                            LevelId = 3,
                            Name = "Advanced Freestyle",
                            Price = 400.00m,
                            Schedule = "Tue, Thu 19:00",
                            UpdatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 8,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Perfect your backstroke form.",
                            Enrolled = 5,
                            LevelId = 2,
                            Name = "Backstroke Mastery",
                            Price = 300.00m,
                            Schedule = "Fri 17:00, Sat 10:00",
                            UpdatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AtlantisSwim.Domain.Entities.Course.CourseImg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseDataId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseDataId");

                    b.ToTable("CourseImgs");
                });

            modelBuilder.Entity("AtlantisSwim.Domain.Entities.Course.CourseLevelData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CourseLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "For those with no prior swimming experience.",
                            Name = "Beginner"
                        },
                        new
                        {
                            Id = 2,
                            Description = "For swimmers comfortable in water.",
                            Name = "Intermediate"
                        },
                        new
                        {
                            Id = 3,
                            Description = "For experienced swimmers refining technique.",
                            Name = "Advanced"
                        });
                });

            modelBuilder.Entity("AtlantisSwim.Domain.Entities.Student.StudentData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("EnrolledOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("SwimmingLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2005, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maria.ionescu@email.com",
                            EnrolledOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Maria",
                            IsActive = true,
                            LastName = "Ionescu",
                            Phone = "0721000001",
                            SwimmingLevel = "Beginner"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2003, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "andrei.popescu@email.com",
                            EnrolledOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Andrei",
                            IsActive = true,
                            LastName = "Popescu",
                            Phone = "0721000002",
                            SwimmingLevel = "Intermediate"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2001, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "elena.constantin@email.com",
                            EnrolledOn = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Elena",
                            IsActive = true,
                            LastName = "Constantin",
                            Phone = "0721000003",
                            SwimmingLevel = "Advanced"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2014, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "andrei.p@gmail.com",
                            EnrolledOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Andrei",
                            IsActive = true,
                            LastName = "Popov",
                            Phone = "0721000004",
                            SwimmingLevel = "Beginner"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(2002, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "elena.d@yahoo.com",
                            EnrolledOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Elena",
                            IsActive = true,
                            LastName = "Dumitru",
                            Phone = "0721000005",
                            SwimmingLevel = "Advanced"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(2008, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mihai.v@gmail.com",
                            EnrolledOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Mihai",
                            IsActive = false,
                            LastName = "Voicu",
                            Phone = "0721000006",
                            SwimmingLevel = "Intermediate"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(2016, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ioana.s@gmail.com",
                            EnrolledOn = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Ioana",
                            IsActive = true,
                            LastName = "Stan",
                            Phone = "0721000007",
                            SwimmingLevel = "Beginner"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(1995, 11, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "george.e@music.com",
                            EnrolledOn = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "George",
                            IsActive = true,
                            LastName = "Enescu",
                            Phone = "0721000008",
                            SwimmingLevel = "Advanced"
                        });
                });

            modelBuilder.Entity("AtlantisSwim.Domain.Entities.SwimmingService.SwimmingServiceData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("ServicePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SwimmingServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ServiceDescription = "One-on-one coaching sessions tailored to individual needs.",
                            ServiceName = "Private Lessons",
                            ServicePrice = 80.00m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ServiceDescription = "Small group lessons with up to 6 participants.",
                            ServiceName = "Group Classes",
                            ServicePrice = 40.00m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ServiceDescription = "Dedicated lane access for personal training sessions.",
                            ServiceName = "Pool Lane Rental",
                            ServicePrice = 25.00m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ServiceDescription = "4 lecții de înot în grup, valabil 1 lună. Durata: 45 min/ședință.",
                            ServiceName = "Abonament 4 Frecvențe",
                            ServicePrice = 1000.00m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ServiceDescription = "8 lecții de înot în grup, valabil 1 lună. Durata: 45 min/ședință.",
                            ServiceName = "Abonament Standard 8 Frecvențe",
                            ServicePrice = 2000.00m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ServiceDescription = "12 antrenamente în grup, valabil 1 lună. Ideal pentru progres rapid.",
                            ServiceName = "Abonament Pro 12 Frecvențe",
                            ServicePrice = 3000.00m
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ServiceDescription = "24 lecții în grup (8/lună × 3 luni). Progres constant, reducere 10%.",
                            ServiceName = "Abonament Standard 3 Luni",
                            ServicePrice = 5400.00m
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ServiceDescription = "36 lecții în grup (12/lună × 3 luni). Progres accelerat, reducere 10%.",
                            ServiceName = "Abonament Pro 3 Luni",
                            ServicePrice = 7500.00m
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ServiceDescription = "5 ședințe individuale 1 la 1, valabil 3 săptămâni. Durata: 45 min/ședință.",
                            ServiceName = "Abonament Individual 5",
                            ServicePrice = 2250.00m
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ServiceDescription = "10 ședințe individuale 1 la 1, valabil 5 săptămâni. Reducere 7%.",
                            ServiceName = "Abonament Individual 10",
                            ServicePrice = 4500.00m
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ServiceDescription = "8 ședințe cu transport tur-retur din Chișinău, valabil 1 lună.",
                            ServiceName = "Abonament Transport Chișinău",
                            ServicePrice = 2400.00m
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ServiceDescription = "8 ședințe cu transport din Ialoveni la Arena Chișinău, valabil 1 lună.",
                            ServiceName = "Abonament Transport Ialoveni",
                            ServicePrice = 2600.00m
                        });
                });

            modelBuilder.Entity("AtlantisSwim.Domain.Entities.User.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@atlantisswim.ro",
                            FirstName = "Admin",
                            LastName = "Atlantis",
                            Password = "Admin@1234",
                            Phone = "0700000001",
                            RegisteredOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = 30,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "coach@atlantisswim.ro",
                            FirstName = "Ioan",
                            LastName = "Marinescu",
                            Password = "Coach@1234",
                            Phone = "0700000002",
                            RegisteredOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = 20,
                            UserName = "coach.ioan"
                        },
                        new
                        {
                            Id = 3,
                            Email = "catalina@atlantisswim.md",
                            FirstName = "Cătălina",
                            LastName = "Moraru",
                            Password = "antrenor1234",
                            Phone = "0700000003",
                            RegisteredOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = 20,
                            UserName = "catalina"
                        },
                        new
                        {
                            Id = 4,
                            Email = "catalin@atlantisswim.md",
                            FirstName = "Cătălin",
                            LastName = "Ciobanu",
                            Password = "antrenor1234",
                            Phone = "0700000004",
                            RegisteredOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = 20,
                            UserName = "catalin"
                        },
                        new
                        {
                            Id = 5,
                            Email = "alexandru@atlantisswim.md",
                            FirstName = "Alexandru",
                            LastName = "Rusu",
                            Password = "antrenor1234",
                            Phone = "0700000005",
                            RegisteredOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = 20,
                            UserName = "alexandru"
                        },
                        new
                        {
                            Id = 6,
                            Email = "admin@school.com",
                            FirstName = "Super",
                            LastName = "Admin",
                            Password = "admin1234",
                            Phone = "0700000006",
                            RegisteredOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = 30,
                            UserName = "super.admin"
                        },
                        new
                        {
                            Id = 7,
                            Email = "director@school.com",
                            FirstName = "Director",
                            LastName = "Ionescu",
                            Password = "admin1234",
                            Phone = "0700000007",
                            RegisteredOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = 30,
                            UserName = "director"
                        },
                        new
                        {
                            Id = 8,
                            Email = "manager@school.com",
                            FirstName = "Manager",
                            LastName = "Stancu",
                            Password = "admin1234",
                            Phone = "0700000008",
                            RegisteredOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = 30,
                            UserName = "manager"
                        },
                        new
                        {
                            Id = 9,
                            Email = "andrei.popov@student.md",
                            FirstName = "Andrei",
                            LastName = "Popov",
                            Password = "elev1234",
                            Phone = "0700000009",
                            RegisteredOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = 1,
                            UserName = "andrei.popov"
                        },
                        new
                        {
                            Id = 10,
                            Email = "elena.dumitru@student.md",
                            FirstName = "Elena",
                            LastName = "Dumitru",
                            Password = "elev1234",
                            Phone = "0700000010",
                            RegisteredOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = 1,
                            UserName = "elena.dumitru"
                        },
                        new
                        {
                            Id = 11,
                            Email = "mihai.voicu@student.md",
                            FirstName = "Mihai",
                            LastName = "Voicu",
                            Password = "elev1234",
                            Phone = "0700000011",
                            RegisteredOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = 1,
                            UserName = "mihai.voicu"
                        });
                });

            modelBuilder.Entity("AtlantisSwim.Domain.Entities.Course.CourseData", b =>
                {
                    b.HasOne("AtlantisSwim.Domain.Entities.Course.CourseLevelData", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("AtlantisSwim.Domain.Entities.Course.CourseImg", b =>
                {
                    b.HasOne("AtlantisSwim.Domain.Entities.Course.CourseData", null)
                        .WithMany("Imgs")
                        .HasForeignKey("CourseDataId");
                });

            modelBuilder.Entity("AtlantisSwim.Domain.Entities.Course.CourseData", b =>
                {
                    b.Navigation("Imgs");
                });
#pragma warning restore 612, 618
        }
    }
}
