version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: atlantisswim_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: atlantisswimdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ebolas77
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d atlantisswimdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
